const data = {
  call_source: ['OAK', 'MISS'],
  city: [
    'BUR',
    'HAM',
    'MIL',
    'MISS',
    'BRAM',
    'ETO',
    'DUN',
    'ANC',
    'WATERDOWN',
    'OAK',
    'SHOP OAK',
    'SHOP MISS',
    'GUELPH',
    'STONEY CREEK',
    'HANNON',
    'NORTH YORK',
    'ACTON',
    'COOLING WOOD',
    'KITCHINER',
    'GEORGE TOWN',
    'GRIMSBY'
  ],
  makes: [
    'MINI',
    'BMW',
    'Genesis',
    'GMC',
    'Roush Performance',
    'Hyundai',
    'Porsche',
    'Nissan',
    'Infiniti',
    'Dodge',
    'Volvo',
    'Ford',
    'Ferrari',
    'Mercedes-Benz',
    'Chevrolet',
    'Honda',
    'Cadillac',
    'Maserati',
    'Acura',
    'Toyota',
    'Volkswagen',
    'Subaru',
    'Jaguar',
    'Mobility Ventures LLC',
    'Mazda',
    'Audi',
    'Kia',
    'Lexus',
    'Fiat',
    'Plymouth',
    'Lincoln',
    'Buick',
    'Land Rover',
    'Jeep',
    'Mitsubishi',
    'Lamborghini',
    'Bentley',
    'Tesla',
    'Rolls-Royce',
    'Isuzu',
    'McLaren Automotive',
    'Ram',
    'Pontiac',
    'Chrysler',
    'Oldsmobile',
    'Rivian',
    'J.K. Motors',
    'London Taxi',
    'Mercury',
    'Saab',
    'Alfa Romeo',
    'Scion',
    'Suzuki',
    'Aston Martin',
    'Peugeot',
    'Renault',
    'TVR Engineering Ltd',
    'CX Automotive',
    'Eagle',
    'Geo',
    'Panoz Auto-Development',
    'Saturn',
    'Lotus',
    'Daewoo',
    'Autokraft Limited',
    'Maybach',
    'Saleen Performance',
    'American Motors Corporation',
    'Bugatti',
    'AM General',
    'Volga Associated Automobile',
    'Bitter Gmbh and Co. Kg',
    'smart',
    'Daihatsu',
    'Sterling',
    'Merkur',
    'Lucid',
    'Pagani',
    'Polestar',
    'Karma',
    'Koenigsegg',
    'Wallace Environmental',
    'BYD',
    'Superior Coaches Div E.p. Dutton',
    'Grumman Allied Industries',
    'Yugo',
    'PAS Inc - GMC',
    'Morgan',
    'Spyker',
    'Hummer',
    'JBA Motorcars, Inc.',
    'Import Trade Services',
    'Excalibur Autos',
    'Federal Coach',
    'Lambda Control Systems',
    'Bertone',
    'Kenyon Corporation Of America',
    'Bill Dovell Motor Car Company',
    'Vinfast',
    'Mcevoy Motors',
    'Environmental Rsch and Devp Corp',
    'VPG',
    'Azure Dynamics',
    'CCC Engineering',
    'Tecstar, LP',
    'Pininfarina',
    'Vixen Motor Company',
    'Panther Car Company Limited',
    'Saleen',
    'Laforza Automobile Inc',
    'Fisker',
    'Evans Automobiles',
    'S and S Coach Company E.p. Dutton',
    'London Coach Co Inc',
    'Dabryan Coach Builders Inc',
    'Isis Imports Ltd',
    'Dacia',
    'Texas Coach Company',
    'Panos',
    'SRT',
    'Ruf Automobile Gmbh',
    'Red Shift Ltd.',
    'Mahindra',
    'RUF Automobile',
    'Kandi',
    'Lordstown',
    'Avanti Motor Corporation',
    'Vector',
    'Consulier Industries Inc',
    'Grumman Olson',
    'General Motors',
    'Quantum Technologies',
    'BMW Alpina',
    'CODA Automotive',
    'Aurora Cars Ltd',
    'PAS, Inc',
    'E. P. Dutton, Inc.',
    'Qvale',
    'Import Foreign Auto Sales Inc',
    'STI',
    'Goldacre',
    'ASC Incorporated',
    'Shelby'
  ],
  status: [
    'STATUS',
    'NOT BOOKED',
    'CANCELLED',
    'PENDING INS',
    'EMAIL REQ',
    'BOOKED',
    'FOLLOW UP'
  ],
  times: [
    '09:00-02:00',
    '10:00-03:00',
    '11:00-04:00',
    '12:00-05:00',
    '01:00-06:00'
  ]
};

export default data;
